### ISSUE TITLE
Crash in show it 

### ISSUE THREAD

**Issue by rezazavvareh1993** [rezarasuolzadeh/pickers#4]
Ive define it but when I want show it, crashing happen.

            DateDialog(
                title = "انتخاب تاریخ",
                confirmTitle = "انتخاب",
                cancelTitle = "انصراف",
                initialDay = 2,
                initialMonth = MonthType.MORDAD,
                initialYear = 1395,
                yearRange = 1380..1410,
                fontFamily = AppFont.HipixiPeydaFontFamily,
                titleColor = MaterialTheme.colorScheme.onSurface,
                yearColor = MaterialTheme.colorScheme.onSurface,
                monthColor = MaterialTheme.colorScheme.onSurface,
                dayColor = MaterialTheme.colorScheme.onSurface,
                slashColor = null,
                confirmColor = MaterialTheme.colorScheme.primary,
                cancelColor = MaterialTheme.colorScheme.onSurface,
                dividerColor = MaterialTheme.colorScheme.surface,
                backgroundColor = MaterialTheme.colorScheme.surfaceContainer,
                backgroundBrush = null,
                outputType = DateOutputType.PERSIAN,
                outputSeparator = '/',
                onCancel = {
                    createStepUiEvent(CreateStepUiEvent.OnHideDatePicker)
                },
                onDateSelect = { dateSelected ->
                    createStepUiEvent(CreateStepUiEvent.OnDateSelected(dateSelected))
                    createStepUiEvent(CreateStepUiEvent.OnHideDatePicker)
                }
            )
            
            
            Error: 
            No static method rememberSnapFlingBehavior(Landroidx/compose/foundation/lazy/LazyListState;Landroidx/compose/runtime/Composer;I)Landroidx/compose/foundation/gestures/FlingBehavior; in class Landroidx/compose/foundation/gestures/snapping/LazyListSnapLayoutInfoProviderKt; or its super classes (declaration of 'androidx.compose.foundation.gestures.snapping.LazyListSnapLayoutInfoProviderKt' appears in /data/app/~~yR0Jek50kMBWQbWvQ3nWKw==/com.akorayan.hipixi-2cFeb1aGFFxVcWFdJYdRZg==/base.apk)

**Comment by rezarasuolzadeh** [comment]
According to your error message, androidx.compose.foundation has a problem on some android API in this version. I will check that and report the result to you 🙏.

**Comment by rezarasuolzadeh** [comment]
I think i solved this problem 😃. First remove my library dependencies from your gradle and download new AAR from [here](https://drive.google.com/file/d/1-061ov6AmfLDRWE59L9eV5VT3PD4jTX2/view?usp=drivesdk) then put the downloaded AAR in your project and in final step add this implementation to your gradle file:
```kotlin
implementation("androidx.constraintlayout:constraintlayout-compose:1.1.0")
```
Now you can run your app and the problem will probably be solved.
Check that and report the result of your test to me please 🙏. If it's solved i will publish new release for library.
@rezazavvareh1993

**Comment by rezarasuolzadeh** [comment]
In new version of the library (1.0.14), this problem has been solved.
